name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm test

      - name: Send Alerts
        if: always()
        uses: ./.github/actions/notify
        with:
          status: ${{ job.status }}
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_to: ${{ secrets.TELEGRAM_CHAT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_issue: 'false'
